site_name: 21525 Hardware
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      

theme:
  icon: 
    repo:fontawesome/brands/git-al
  name: material
  palette:
    scheme: slate
    primary: blue
  extra_css:
    - stylesheets/extra.css
  font:
    text: Helvetica Neue
    code: Roboto Mono
  language: en
  logo: assets/21525Logo.svg
  favicon: assets/21525Logo.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.expand
    - navigation.tabs.sticky
    - content.tabs.link
  
extra:
  consent:
    title: Cookie consent
    description: >- 
      Cookies help us use google fonts which make my life setting up this website easier
      Consider enabling them so font's arent broke, and we can show off to the judges how 
      many people came and saw our website!
    actions:
      - accept
      - manage
      - reject
  analytics:
      provider: google
      property: G-VXSFKQ315X
copyright: >
    Copyright &copy; 2022 Grady Conwell, Sanjith Cherumandanda, Victor He, Warren Lam, Robyn Lam, Joshua Sugino, David Becker-Peral, Noah Balderson –
    <a href="#__consent">Change cookie settings</a>

plugins:
  - search
repo_url: https://github.com/Blockheads-2/Blockheads2022-23-Hardware
repo_name: Blockheads-2/Blockheads2022-23-Hardware

nav:     
    - About Us:
        - About Us: index.md
    - Hardware:
        - MiniSwerve: Swerve.md
        - Robot Arm: Lifter.md
    - Contact: 
        - Contact: Contact.md
